import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const dynamic = "force-dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IGIIDeation Judging and Evaluating Platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="text-center text-red-500">
          <span className="font-semibold">
            This system is still in Beta phase and under testing!
          </span>{" "}
          <br />
          The system will fully online on 8 February 2024 12:00 a.m until 12
          February 2024 12:00 pm <br /> <br />
          If you encounter any bug or broken feature, please report to
          hakimnazry@gmail.com <br />
          Thank you for your cooperation.
        </div> */}
        {children}
      </body>
    </html>
  );
}
